// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const authConfig = {
  aws_project_region: 'ap-northeast-1',
  aws_cognito_identity_pool_id:
    'ap-northeast-1:1f53a4b5-124f-4fc3-9dff-0abab977d827',
  aws_cognito_region: 'ap-northeast-1',
  aws_user_pools_id: 'ap-northeast-1_vx2rxG09m',
  aws_user_pools_web_client_id: '45i472aucdijm9clh6u06p79ap',
  oauth: {},
};

export default authConfig;
